/// Flutter icons GenshinDb
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  GenshinDb
///      fonts:
///       - asset: fonts/GenshinDb.ttf
///
///
/// * MFG Labs, Copyright (C) 2012 by Daniel Bruce
///         Author:    MFG Labs
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://www.mfglabs.com/
/// * Font Awesome 5, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL (https://github.com/FortAwesome/Font-Awesome/blob/master/LICENSE.txt)
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
///
import 'package:flutter/widgets.dart';

class GenshinDb {
  GenshinDb._();

  static const _kFontFam = 'GenshinDb';
  static const _kFontPkg = null;

  static const IconData male = IconData(0xe800, fontFamily: _kFontFam);
  static const IconData female = IconData(0xe801, fontFamily: _kFontFam);
  static const IconData cogs = IconData(0xf085, fontFamily: _kFontFam);
  static const IconData filter = IconData(0xf0b0, fontFamily: _kFontFam);
  static const IconData sliders_h = IconData(0xf1de, fontFamily: _kFontFam);
}
