targets:
  $default:
    builders:
      hive_ce_generator:hive_adapters_generator:
        enabled: False
      hive_ce_generator:hive_registrar_intermediate_generator:
        enabled: False
      hive_ce_generator:hive_type_adapter_generator:
        generate_for:
          - lib/domain/models/entities/**
      envied_generator:envied:
        generate_for:
          - lib/env.dart
      json_serializable:
        generate_for:
          - lib/domain/models/backup/**
          - lib/domain/models/db/**
          - lib/domain/models/dtos/**
          - lib/domain/models/settings/**
      freezed:
        options:
          format: false
        generate_for:
          - lib/application/**
          - lib/domain/models/**
      mockito:mockBuilder:
        generate_for:
          - test/mocks.dart
          - test/nice_mocks.dart