/// Flutter icons GenshinDb
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  GenshinDb
///      fonts:
///       - asset: fonts/GenshinDb.ttf
///
///
/// * MFG Labs, Copyright (C) 2012 by Daniel Bruce
///         Author:    MFG Labs
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://www.mfglabs.com/
/// * RPG Awesome, Copyright (c) 2014, Daniela Howe
///         Author:    Daniela Howe & Ivan Montiel
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://nagoshiashumari.github.io/Rpg-Awesome/
/// * Font Awesome 5, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL (https://github.com/FortAwesome/Font-Awesome/blob/master/LICENSE.txt)
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
///
import 'package:flutter/widgets.dart';

class GenshinDb {
  GenshinDb._();

  static const _kFontFam = 'GenshinDb';
  static const String? _kFontPkg = null;

  static const IconData male = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData female = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData crossed_swords = IconData(0xe97d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cubes = IconData(0xe986, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData hive_emblem = IconData(0xea00, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData level_four = IconData(0xea24, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData level_three_advanced = IconData(0xea25, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData overmind = IconData(0xea55, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData reactor = IconData(0xea7b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData trefoil_lily = IconData(0xead4, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cogs = IconData(0xf085, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData filter = IconData(0xf0b0, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sliders_h = IconData(0xf1de, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
