enum StatType {
  all,
  none,
  atk,
  atkPercentage,
  defPercentage,
  critAtk,
  critRate,
  critRatePercentage,
  critDmgPercentage,
  elementaryMaster,
  hpPercentage,
  physDmgPercentage,
  physDmgBonus,
  energyRechargePercentage,
}
